### ISSUE TITLE
Easy Glossary for Total Beginners

### ISSUE THREAD

**Issue by yuri-la-torre-ortiz** [JuliaAcademy/JuliaTutorials#40]
Hi there.  It's my first day coding & I really appreciate this resource and I find it more or less easy to follow.  However, I would recommend either providing a link to a glossary or simply having a glossary available for absolute beginners to explain terminology such as those referring to the various data types & examples given.  Just to make the language a bit more accessible.  

I'm enjoying the tutorial & like the small exercises.  I believe the very first page should also include an exercise or two to make sure people understand how to search for documents.  It was also unclear if the information was relevant because of the heading "Jupyter Notebook."

Thank you again for the hard work & service.

**Comment by logankilpatrick** [comment]
I would say the best course of action would be to point people to https://julialang.org/learning/ and have them go to the "resources" section. @yuri-la-torre-ortiz which tutorials do you think need this?

**Comment by logankilpatrick** [comment]
Great idea, let's do it here: https://github.com/JuliaCommunity/StartHere.jl#glossary
