### ISSUE TITLE
Re-name repo and transfer it 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaAcademy/JuliaTutorials#67]
@ViralBShah thoughts on either renaming and removing references to JuliaBox or renaming, removing references to JuliaBox, and transferring to JuliaAcademy?

**Comment by ViralBShah** [comment]
We can do it once we shut down JuliaBox, which is a few weeks away.

**Comment by NHDaly** [comment]
@logankilpatrick There's also this related issue tracking the same thing, i think: #25

**Comment by ViralBShah** [comment]
Let's track it here since that one is closed.
