### ISSUE TITLE
error in installing plotlyJS and ORCA 

### ISSUE THREAD

**Issue by RohitKumar23-11** [JuliaAcademy/JuliaTutorials#73]
every time I run this codes 
using Pkg
Pkg.add("ORCA")
Pkg.add("PlotlyJS")
using PlotlyJS
Pkg.build("WebIO")
Pkg.build("ORCA")
plotlyjs()
 I get these error what I should do,

ORCA → `C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\packages\ORCA\jdK40\deps\build.log`
┌ Error: Error building `ORCA`: 
│ internal/modules/cjs/loader.js:800
│     throw err;
│     ^
│ 
│ Error: Cannot find module './internal/streams/stream'
│ Require stack:
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_readable.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\readable.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\tracker-stream.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\tracker-group.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\index.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\npmlog\log.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\bin\npm-cli.js
│     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
│     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
│     at Module.require (internal/modules/cjs/loader.js:852:19)
│     at require (internal/modules/cjs/helpers.js:74:18)
│     at Object. (C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_readable.js:50:14)
│     at Module._compile (internal/modules/cjs/loader.js:959:30)
│     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
│     at Module.load (internal/modules/cjs/loader.js:815:32)
│     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
│     at Module.require (internal/modules/cjs/loader.js:852:19) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\lib\\_stream_readable.js',   
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\readable.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\tracker-stream.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\tracker-group.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\index.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\npmlog\\log.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\bin\\npm-cli.js'
│   ]
│ }
│ internal/modules/cjs/loader.js:800
│     throw err;
│     ^
│ 
│ Error: Cannot find module './internal/streams/stream'
│ Require stack:
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_readable.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\readable.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\tracker-stream.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\tracker-group.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\index.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\npmlog\log.js
│ - C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\bin\npm-cli.js
│     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
│     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
│     at Module.require (internal/modules/cjs/loader.js:852:19)
│     at require (internal/modules/cjs/helpers.js:74:18)
│     at Object. (C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_readable.js:50:14)
│     at Module._compile (internal/modules/cjs/loader.js:959:30)
│     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
│     at Module.load (internal/modules/cjs/loader.js:815:32)
│     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
│     at Module.require (internal/modules/cjs/loader.js:852:19) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\lib\\_stream_readable.js',   
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\readable.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\tracker-stream.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\tracker-group.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\index.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\npmlog\\log.js',
│     'C:\\Users\\Acer\\.juliapro\\JuliaPro_v1.4.2-1\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\bin\\npm-cli.js'
│   ]
│ }
│ ERROR: LoadError: failed process: Process(`'C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\npm.cmd' config set scripts-prepend-node-path true`, ProcessExited(1)) [1]     
│ 
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at .\process.jl:440
│  [3] run at .\process.jl:438 [inlined]
│  [4] main() at C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\packages\ORCA\jdK40\deps\build.jl:4
│  [5] top-level scope at C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\packages\ORCA\jdK40\deps\build.jl:30     
│  [6] include(::String) at .\client.jl:439
│  [7] top-level scope at none:5
│ in expression starting at C:\Users\Acer\.juliapro\JuliaPro_v1.4.2-1\packages\ORCA\jdK40\deps\build.jl:30   
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.4.2\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892

**Comment by logankilpatrick** [comment]
Hm, I am not getting this error on Julia 1.5 locally. Let me try my Julia Pro installation and see what I get.

**Comment by PallHaraldsson** [comment]
I tried and get:

```
julia> plotlyjs()
ERROR: UndefVarError: plotlyjs not defined
```

ORCA is deprecated, and I'm probably on latest versions (and Julia 1.6). It should still work on older, but we should update tutorials for the new reality.

**Comment by logankilpatrick** [comment]
You need to do `using plots` to get plotly()

**Comment by PallHaraldsson** [comment]
Yes, was just trying (as reported), and I get I can confirm, I get no error (on Julia 1.6), with capitalized ("plot" is not enough):

```
julia> using Plots
julia> plotlyjs();
┌ Warning: ORCA.jl has been deprecated and all savefig functionality
│ has been implemented directly in PlotlyBase itself.
│ 
│ By implementing in PlotlyBase.jl, the savefig routines are automatically
│ available to PlotlyJS.jl also.
└ @ ORCA ~/.julia/packages/ORCA/U5XaN/src/ORCA.jl:8
```

**Comment by logankilpatrick** [comment]
@PallHaraldsson closing this for now but if you run into further issues, please ping me here.
