### ISSUE TITLE
[README.md] Link to download doesn't work. Gives 404.

### ISSUE THREAD

**Issue by pieteromt** [JuliaAcademy/JuliaTutorials#82]
The link to download doesn't work, and gives an 404.

Wrong link:
https://github.com/JuliaComputing/JuliaBoxTutorials/archive/master.zip

Correct link:
https://github.com/JuliaAcademy/JuliaTutorials/archive/refs/heads/main.zip

**Comment by logankilpatrick** [comment]
Hey! Can you turn this into a Pull Request? happy to merge and thanks for pointing this out.

**Comment by pieteromt** [comment]
> Hey! Can you turn this into a Pull Request? happy to merge and thanks for pointing this out.

Done

**Comment by logankilpatrick** [comment]
Merged!
